// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrRakktsR39X8_etCFXwgAGi6GpcJIyR8',
    appId: '1:706134463439:web:bd2888805df31105d5b8ba',
    messagingSenderId: '706134463439',
    projectId: 'internship-project-f60b4',
    authDomain: 'internship-project-f60b4.firebaseapp.com',
    databaseURL: 'https://internship-project-f60b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internship-project-f60b4.appspot.com',
    measurementId: 'G-76RXW5HDV6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRkYQ1dEaGWQYW4R2epB0JaFwZOpiTQMw',
    appId: '1:706134463439:ios:571bb4ac88e1bd15d5b8ba',
    messagingSenderId: '706134463439',
    projectId: 'internship-project-f60b4',
    databaseURL: 'https://internship-project-f60b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internship-project-f60b4.appspot.com',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw4FeFYVxPuka4ZqS1xOdIDRcpKu4ZSqs',
    appId: '1:706134463439:android:35eb41331b6218c9d5b8ba',
    messagingSenderId: '706134463439',
    projectId: 'internship-project-f60b4',
    databaseURL: 'https://internship-project-f60b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internship-project-f60b4.appspot.com',
  );

}